name: Tencent-Cloud-CDN-Purge-Paths-Cache
description: This action purges paths cache for Tencent Cloud CDN via Node SDK API.
branding:
  icon: refresh-ccw
  color: yellow
inputs:
  secret-id:
    description: The secretId used to authenticate with Tencent Cloud.
    required: true
  secret-key:
    description: The accessKeySecret used to authenticate with Tencent Cloud.
    required: true
  paths:
    description: "Directory listing, needs to include protocol header http: or https:"
    required: true
  flush_type:
    description: "flush type: flush or delete"
    default: "delete"
    required: true
  url_encode:
    description: "url encode"
    type: boolean
    default: false
    required: false
  area:
    description: "flush area: mainland or overseas"
    required: false

runs:
  using: node20
  main: bootstrap.js
