name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 2

    steps:
      - uses: actions/checkout@v4

      # default test
      - uses: ./
        with:
          paths: |
            https://test.ksh7.com
            https://test-2.ksh7.com
          secret-id: ${{secrets.SECRET_ID}}
          secret-key: ${{secrets.SECRET_KEY}}
          flush_type: delete
          url_encode: false
          area: mainland

  test-passing:
    needs: [test]
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - run: echo "All tests have passed."
